name: Eva Lacy
description: Technology, Philosophy and Politics
meta_description: "Eva Lacy, Technology, Philosophy and Politics"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
exclude: [Gemfile, buildspec.yml, LICENSE.txt, README.md, sync.s3.sh]
domain_name: 'https://www.lacy.ie'
plugins: [jekyll-paginate, jekyll-sitemap]
excerpt_separator: "<!-- more -->"

# Details for the RSS feed generator
url:            'https://www.lacy.ie'
author:         'Eva Lacy'
